[2019-02-23 17:03:23,611] INFO Unable to read additional data from server sessionid 0x1000212664f0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:24,819] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:24,821] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:26,441] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:26,442] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:26,982] INFO [GroupCoordinator 0]: Member kafka-python-1.4.4-f7fbbd4b-b299-4ee6-9236-42b9f4fb0d9b in group velib-monitor-stations has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-02-23 17:03:26,982] INFO [GroupCoordinator 0]: Preparing to rebalance group velib-monitor-stations in state PreparingRebalance with old generation 53 (__consumer_offsets-17) (reason: removing member kafka-python-1.4.4-f7fbbd4b-b299-4ee6-9236-42b9f4fb0d9b on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-02-23 17:03:26,983] INFO [GroupCoordinator 0]: Group velib-monitor-stations with generation 54 is now empty (__consumer_offsets-17) (kafka.coordinator.group.GroupCoordinator)
[2019-02-23 17:03:28,524] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:28,525] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:30,435] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:30,436] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:32,283] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:32,283] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:33,536] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:33,537] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:34,532] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-23 17:03:34,532] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-23 17:03:34,533] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-02-23 17:03:34,534] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-02-23 17:03:35,375] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:35,376] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:35,480] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-02-23 17:03:36,595] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:36,596] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:37,764] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:37,764] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:39,009] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-23 17:03:39,010] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
